name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: build
      run: |
        npm install
        npm run build
    - name: archive
      run: |
        tar -cf tmp.zip dist/business-calendar
        ls -a
    - uses: nekitcorp/yandex-storage-website-action@v2
      with:
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        bucket: ${{ secrets.BUCKET }}/frontend
        include: |
          *.zip
