name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install, test
      run: |
        npm install
        npm run build
        ls dist/business-calendar

  archive:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: create archive
      run: |
        tar -cf tmp.zip dist/business-calendar
        ls
