name: Deploy Frontend App

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: tmp
      run: |
        output=${{ vars.BRANCH }}
        echo ::set-output name=script_output::$output
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      env: 
        FILE: bc-frontend-${{ vars.BRANCH }}-${{ vars.HASH }}-${{ vars.DATE }}.zip
        BRANCH: ${script_output}
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: BRANCH,SHA,FILE
        script: |
          echo "$SHA"
          echo "$BRANCH"
          
