name: Deploy Frontend App

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set vars
      id: vars
      run: |
        echo ::set-output name=BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=HASH::$(git rev-parse --short ${GITHUB_SHA})
        echo ::set-output name=DATE::$(date +'%d-%m-%Y')
        echo ::set-output name=FILENAME::${"bc-frontend-${BRANCH}-${HASH}-${DATE}"}
    - name: test
      run: |
        echo ${{ steps.vars.outputs.BRANCH }}
        echo ${{ steps.vars.outputs.HASH }}
        echo ${{ steps.vars.outputs.DATE }}
        echo ${{ steps.vars.outputs.FILENAME }}
    


    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      env: 
        FILE: bc-frontend-${{ vars.BRANCH }}-${{ vars.HASH }}-${{ vars.DATE }}.zip
        BRANCH: ${{ env.BRANCH }}
        SHA: ${{ github.sha }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: BRANCH,SHA,FILE
        script: |
          echo "$SHA"
          echo "$BRANCH"
          
