name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install, test
      run: |
        npm install
        npm run build
        pwd
        ls -a
        ls dist/business-calendar
    - name: archive
      run: |
        tar -cf tmp.zip dist/business-calendar
        ls -a
    - uses: MrMeison/yc-object-storage-action@1.2.1
      with:
        accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
        secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
        bucketName: ${{ secrets.BUCKET }}
        include: /*.zip
