name: Deploy Frontend App

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: tmp
      run: echo "${{ vars.BRANCH }}"
    - name: executing remote ssh commands using ssh key
      
      uses: appleboy/ssh-action@v1.0.0
      env: 
        BRANCH: ${ vars.BRANCH }
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: BRANCH
        script: |
          echo "$BRANCH"
          
